# login splashscreen code
image splash = "gui/login.jpg"

# opening crawl
image crawl = Movie(play = "CyberBullyCrawl.webm", loops = 1)

# black background
image black = "black.jpg"

# items
image phone_and_hand = "characters/items/phone_and_hand.png"

# logan
image logan_angry1 = "characters/logan/logan_angry1.png"
image logan_angry2 = "characters/logan/logan_angry2.png"
image logan_angry3 = "characters/logan/logan_angry3.png"
image logan_dizzy1 = "characters/logan/logan_dizzy1.png"
image logan_dizzy2 = "characters/logan/logan_dizzy2.png"
image logan_dizzy3 = "characters/logan/logan_dizzy3.png"
image logan_normal1 = "characters/logan/logan_normal1.png"
image logan_normal2 = "characters/logan/logan_normal2.png"
image logan_normal3 = "characters/logan/logan_normal3.png"
image logan_normal4 = "characters/logan/logan_normal4.png"
image logan_normal5 = "characters/logan/logan_normal5.png"
image logan_normal6 = "characters/logan/logan_normal6.png"
image logan_normal7 = "characters/logan/logan_normal7.png"
image logan_panic1 = "characters/logan/logan_panic1.png"
image logan_panic2 = "characters/logan/logan_panic2.png"
image logan_panic3 = "characters/logan/logan_panic3.png"
image logan_sitting1 = "characters/logan/logan_sitting1.png"
image logan_sitting2 = "characters/logan/logan_sitting2.png"
image logan_sitting3 = "characters/logan/logan_sitting3.png"
image logan_sitting4 = "characters/logan/logan_sitting4.png"
image logan_sitting5 = "characters/logan/logan_sitting5.png"
image logan_sitting6 = "characters/logan/logan_sitting6.png"
image logan_smartphone1 = "characters/logan/logan_smartphone1.png"
image logan_smartphone2 = "characters/logan/logan_smartphone2.png"
image logan_smartphone3 = "characters/logan/logan_smartphone3.png"
image logan_talking1 = "characters/logan/logan_talking1.png"
image logan_talking2 = "characters/logan/logan_talking2.png"
image logan_talking3 = "characters/logan/logan_talking3.png"
image logan_talking4 = "characters/logan/logan_talking4.png"
image logan_talking5 = "characters/logan/logan_talking5.png"
image logan_talking6 = "characters/logan/logan_talking6.png"
image logan_talking7 = "characters/logan/logan_talking7.png"
image logan_upset1 = "characters/logan/logan_upset1.png"
image logan_upset2 = "characters/logan/logan_upset2.png"
image logan_upset3 = "characters/logan/logan_upset3.png"
image logan_upset4 = "characters/logan/logan_upset4.png"
image logan_upset5 = "characters/logan/logan_upset5.png"
image logan_upset6 = "characters/logan/logan_upset6.png"
image logan_tray = "characters/logan/logan_tray.png"
image logan_running = "characters/logan/logan_running.png"
image logan_spraycan = "characters/logan/logan_spraycan.png"
image logan_ground = "characters/logan/logan_ground.png"
image logan_lunge = "characters/logan/logan_lunge.png"

# hex
image bully_bandana1 = "characters/hex/bully_bandana1.png"
image bully_bandana2 = "characters/hex/bully_bandana2.png"
image bully_bandana = "characters/hex/bully_bandana3.png"
image bully_bandana4 = "characters/hex/bully_bandana4.png"
image bully_bandana5 = "characters/hex/bully_bandana5.png"
image bully_bandana6 = "characters/hex/bully_bandana6.png"
image bully_bandana7 = "characters/hex/bully_bandana7.png"
image bully_bandana8 = "characters/hex/bully_bandana8.png"
image bully_bandana9 = "characters/hex/bully_bandana9.png"
image bully_bandana10 = "characters/hex/bully_bandana10.png"
image bully_bat1 = "characters/hex/bully_bat1.png"
image bully_bat2 = "characters/hex/bully_bat2.png"
image bully_bat3 = "characters/hex/bully_bat3.png"
image bully_laughing1 = "characters/hex/bully_laughing1.png"
image bully_laughing2 = "characters/hex/bully_laughing2.png"
image bully_normal1 = "characters/hex/bully_normal1.png"
image bully_normal2 = "characters/hex/bully_normal2.png"
image bully_normal3 = "characters/hex/bully_normal3.png"
image bully_normal4 = "characters/hex/bully_normal4.png"
image bully_normal5 = "characters/hex/bully_normal5.png"
image bully_normal6 = "characters/hex/bully_normal6.png"
image bully_normal7 = "characters/hex/bully_normal7.png"
image bully_normal8 = "characters/hex/bully_normal8.png"
image bully_shrugging1 = "characters/hex/bully_shrugging1.png"
image bully_shrugging2 = "characters/hex/bully_shrugging2.png"
image bully_sitting1 = "characters/hex/bully_sitting1.png"
image bully_sitting2 = "characters/hex/bully_sitting2.png"
image bully_sitting3 = "characters/hex/bully_sitting3.png"
image bully_sitting4 = "characters/hex/bully_sitting4.png"
image bully_sitting5 = "characters/hex/bully_sitting5.png"
image bully_sitting6 = "characters/hex/bully_sitting6.png"
image bully_sitting7 = "characters/hex/bully_sitting7.png"
image bully_sitting8 = "characters/hex/bully_sitting8.png"
image bully_smartphone1 = "characters/hex/bully_smartphone1.png"
image bully_smartphone2 = "characters/hex/bully_smartphone2.png"
image bully_smartphone3 = "characters/hex/bully_smartphone3.png"
image bully_smartphone4 = "characters/hex/bully_smartphone4.png"
image bully_talking1 = "characters/hex/bully_talking1.png"
image bully_talking2 = "characters/hex/bully_talking2.png"
image bully_talking3 = "characters/hex/bully_talking3.png"
image bully_spraycan = "characters/hex/bully_spraycan.png"
image bully_ground = "characters/hex/bully_ground.png"

# henchmen
image henchman1_normal1 = "characters/henchman1/henchman1_normal1.png"
image henchman1_normal2 = "characters/henchman1/henchman1_normal2.png"
image henchman1_normal3 = "characters/henchman1/henchman1_normal3.png"
image henchman1_sitting1 = "characters/henchman1/henchman1_sitting1.png"
image henchman1_sitting2 = "characters/henchman1/henchman1_sitting2.png"
image henchman1_sitting3 = "characters/henchman1/henchman1_sitting3.png"
image henchman1_laughing1 = "characters/henchman1/henchman1_laughing1.png"
image henchman1_smartphone = "characters/henchman1/henchman1_smartphone.png"
image henchman2_normal1= "characters/henchman2/henchman2_normal1.png"
image henchman2_normal2 = "characters/henchman2/henchman2_normal2.png"
image henchman2_normal3 = "characters/henchman2/henchman2_normal3.png"
image henchman2_sitting1 = "characters/henchman2/henchman2_sitting1.png"
image henchman2_sitting2 = "characters/henchman2/henchman2_sitting2.png"
image henchman2_sitting3 = "characters/henchman2/henchman2_sitting3.png"
image henchman2_sitting4 = "characters/henchman2/henchman2_sitting4.png"

# students
image boy1_normal1 = "characters/boy1/boy1_normal1.png"
image boy1_normal2 = "characters/boy1/boy1_normal2.png"
image boy1_normal3 = "characters/boy1/boy1_normal3.png"
image boy1_sitting1 = "characters/boy1/boy1_sitting1.png"
image boy1_sitting2 = "characters/boy1/boy1_sitting2.png"
image boy1_sitting3 = "characters/boy1/boy1_sitting3.png"
image boy2_normal1 = "characters/boy2/boy2_normal1.png"
image boy2_normal2 = "characters/boy2/boy2_normal2.png"
image boy2_sitting1 = "characters/boy2/boy2_sitting1.png"
image boy2_sitting2 = "characters/boy2/boy2_sitting2.png"
image boy2_sitting3  = "characters/boy2/boy2_sitting3.png"
image girl1_normal1 = "characters/girl1/girl1_normal1.png"
image girl1_normal2 = "characters/girl1/girl1_normal2.png"
image girl1_normal3 = "characters/girl1/girl1_normal3.png"
image girl1_sitting1 = "characters/girl1/girl1_sitting1.png"
image girl1_sitting2 = "characters/girl1/girl1_sitting2.png"
image girl1_sitting3 = "characters/girl1/girl1_sitting3.png"
image girl2_normal1 = "characters/girl2/girl2_normal1.png"
image girl2_normal2 = "characters/girl2/girl2_normal2.png"
image girl2_sitting1 = "characters/girl2/girl2_sitting1.png"
image girl2_sitting2 = "characters/girl2/girl2_sitting2.png"
image girl3_normal1 = "characters/girl3/girl3_normal1.png"
image girl3_normal2 = "characters/girl3/girl3_normal2.png"
image girl3_sitting1 = "characters/girl3/girl3_sitting1.png"
image girl3_sitting2 = "characters/girl3/girl3_sitting2.png"

# group
image group1 = "characters/group/group1.png"
image group2 = "characters/group/group2.png"
image group3 = "characters/group/group3.png"
image group4 = "characters/group/group4.png"

# teacher1 - Ms. VanStay
image melton_normal1 = "characters/teacher1/teacher1_normal1.png"
image melton_normal2 = "characters/teacher1/teacher1_normal2.png"
image melton_normal3 = "characters/teacher1/teacher1_normal3.png"
image melton_sitting1 = "characters/teacher1/teacher1_sitting1.png"
image melton_sitting2 = "characters/teacher1/teacher1_sitting2.png"
image melton_sitting3 = "characters/teacher1/teacher1_sitting3.png"

# teacher2 - Mrs. Smith
image smith_normal1 = "characters/teacher2/teacher2_normal1.png"
image smith_normal2 = "characters/teacher2/teacher2_normal2.png"
image smith_normal3 = "characters/teacher2/teacher2_normal3.png"
image smith_normal4 = "characters/teacher2/teacher2_normal4.png"
image smith_sitting1 = "characters/teacher2/teacher2_sitting1.png"
image smith_sitting2 = "characters/teacher2/teacher2_sitting2.png"

# lunch lady - Doris
image doris_normal1 = "characters/lunchlady/lunchlady1.png"
image doris_normal2 = "characters/lunchlady/lunchlady2.png"

# homeroom
image homeroom_splash = "scenes/homeroom/homeroom_splash.jpg"
image homeroom1 = "scenes/homeroom/homeroom1.jpg"
image homeroom2 = "scenes/homeroom/homeroom2.jpg"
image homeroom3 = "scenes/homeroom/homeroom3.jpg"
image homeroom4 = "scenes/homeroom/homeroom4.jpg"
image homeroom5 = "scenes/homeroom/homeroom5.jpg"
image homeroom6 = "scenes/homeroom/homeroom6.jpg"
image homeroom7 = "scenes/homeroom/homeroom7.jpg"
image homeroom8 = "scenes/homeroom/homeroom8.jpg"
image homeroom9 = "scenes/homeroom/homeroom9.jpg"
image homeroom10 = "scenes/homeroom/homeroom10.jpg"
image homeroom11 = "scenes/homeroom/homeroom11.jpg"
image homeroom12 = "scenes/homeroom/homeroom12.jpg"
image homeroom13 = "scenes/homeroom/homeroom13.jpg"

image ear_flick1 = "scenes/homeroom/ear_flick1.jpg"
image ear_flick2 = "scenes/homeroom/ear_flick2.jpg"
image ear_flick3 = "scenes/homeroom/ear_flick3.jpg" 

# gym
image gym_splash = "scenes/gym/gym_splash.jpg"
image gym1_bg = "scenes/gym/gym1_bg.jpg"
image gym1 = "scenes/gym/gym1.jpg"
image gym2 = "scenes/gym/gym2.jpg"
image gym3 = "scenes/gym/gym3.jpg"
image gym4 = "scenes/gym/gym4.jpg"
image gym5 = "scenes/gym/gym5.jpg"

# bathroom
image bathroom_splash = "scenes/bathroom/bathroom_splash.jpg"
image bathroom1_bg = "scenes/bathroom/bathroom1_bg.jpg"
image bathroom3_bg = "scenes/bathroom/bathroom3_bg.png"
image bathroom1 = "scenes/bathroom/bathroom1.jpg"
image bathroom2 = "scenes/bathroom/bathroom2.jpg"
image bathroom3 = "scenes/bathroom/bathroom3.jpg"
image bathroom4 = "scenes/bathroom/bathroom4.jpg"
image bathroom5 = "scenes/bathroom/bathroom5.jpg"
image bathroom6 = "scenes/bathroom/bathroom6.jpg"

# cafeteria
image cafeteria_splash = "scenes/cafeteria/cafeteria_splash.jpg"
image cafeteria1 = "scenes/cafeteria/cafeteria1.jpg"
image cafeteria2 = "scenes/cafeteria/cafeteria2.jpg"
image cafeteria3 = "scenes/cafeteria/cafeteria3.jpg"
image cafeteria4 = "scenes/cafeteria/cafeteria4.jpg"
image cafeteria5 = "scenes/cafeteria/cafeteria5.jpg"
image cafeteria6 = "scenes/cafeteria/cafeteria6.jpg"
image cafeteria7 = "scenes/cafeteria/cafeteria7.jpg"
image cafeteria8 = "scenes/cafeteria/cafeteria8.png"
image cafeteria9 = "scenes/cafeteria/cafeteria9.jpg"
image cafeteria10 = "scenes/cafeteria/cafeteria10.jpg"
image cafeteria11 = "scenes/cafeteria/cafeteria11.jpg"
image cafeteria12 = "scenes/cafeteria/cafeteria12.jpg"

# art
image art_splash = "scenes/art/art_splash.jpg"
image art1 = "scenes/art/art1.jpg"
image art2_2 = "scenes/art/art2_2.jpg"
image art2 = "scenes/art/art2.jpg"
image art3 = "scenes/art/art3.jpg"
image art4 = "scenes/art/art4.jpg"
image art5 = "scenes/art/art5.jpg"
image art6 = "scenes/art/art6.jpg"
image art7 = "scenes/art/art7.jpg"
image art8 = "scenes/art/art8.jpg"
image logan_painting = "scenes/art/logan_painting.jpg"
image logan_painting2 = "scenes/art/logan_painting2.jpg"

# schoolyard main
image schoolyard_splash = "scenes/schoolyard/schoolyard_splash.jpg"
image ripping_painting = "scenes/schoolyard/ripping_painting.jpg"
image schoolyard1 = "scenes/schoolyard/schoolyard1.jpg"
image schoolyard2 = "scenes/schoolyard/schoolyard2.jpg"
image schoolyard3 = "scenes/schoolyard/schoolyard3.jpg"
image schoolyard4 = "scenes/schoolyard/schoolyard4.jpg"
image schoolyard5 = "scenes/schoolyard/schoolyard5.jpg"
image schoolyard6 = "scenes/schoolyard/schoolyard6.jpg"

# schoolyard option a
image schoolyard7 = "scenes/schoolyard/option_a/schoolyard7.jpg"
image schoolyard8 = "scenes/schoolyard/option_a/schoolyard8.jpg"
image schoolyard9 = "scenes/schoolyard/option_a/schoolyard9.jpg"
image schoolyard10 = "scenes/schoolyard/option_a/schoolyard10.jpg"

# schoolyard option b
image schoolyard11 = "scenes/schoolyard/option_b/schoolyard11.jpg"
image schoolyard12 = "scenes/schoolyard/option_b/schoolyard12.jpg"
image schoolyard13 = "scenes/schoolyard/option_b/schoolyard13.jpg"
image schoolyard14 = "scenes/schoolyard/option_b/schoolyard14.jpg"

# schoolyard special
image schoolyard15 = "scenes/schoolyard/option_special/schoolyard15.jpg"
image schoolyard16 = "scenes/schoolyard/option_special/schoolyard16.jpg"
image schoolyard17 = "scenes/schoolyard/option_special/schoolyard17.jpg"
image schoolyard18 = "scenes/schoolyard/option_special/schoolyard18.jpg"

# after school
image after_school_splash = "scenes/after_school/after_school_splash.jpg"
image after_school1 = "scenes/after_school/after_school1.jpg"
image after_school2 = "scenes/after_school/after_school2.jpg"
image after_school3 = "scenes/after_school/after_school3.jpg"
image after_school4 = "scenes/after_school/after_school4.jpg"
image after_school5 = "scenes/after_school/after_school5.jpg"
image after_school6 = "scenes/after_school/after_school6.jpg"
image after_school7 = "scenes/after_school/after_school7.jpg"

# after school option a
image after_school8 = "scenes/after_school/after_school_a/after_school8.jpg"
image after_school9 = "scenes/after_school/after_school_a/after_school9.jpg"
image after_school10 = "scenes/after_school/after_school_a/after_school10.jpg"
image after_school11 = "scenes/after_school/after_school_a/after_school11.jpg"
image after_school12 = "scenes/after_school/after_school_a/after_school12.jpg"

# after school obtion b
image after_school13 = "scenes/after_school/after_school_b/after_school13.jpg"
image after_school14 = "scenes/after_school/after_school_b/after_school14.jpg"
image after_school15 = "scenes/after_school/after_school_b/after_school15.jpg"
image after_school16 = "scenes/after_school/after_school_b/after_school16.jpg"
image after_school17 = "scenes/after_school/after_school_b/after_school17.jpg"

# after school special
image after_school18 = "scenes/after_school/after_school_special/after_school18.jpg"
image after_school19 = "scenes/after_school/after_school_special/after_school19.jpg"
image after_school20 = "scenes/after_school/after_school_special/after_school20.jpg"
image after_school21 = "scenes/after_school/after_school_special/after_school21.jpg"